services:
  scems_postgres:
    container_name: scems_postgres
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    user: postgres
    volumes:
      - scems_postgres_volume:/var/lib/postgresql/data
    env_file:
      - envs/.env.postgres
    networks:
      - scems_network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "scemsdb"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

volumes:
  scems_postgres_volume:
    name: scems_postgres_volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/postgres/data
